export default {
  HOME: {
    CHANGE_SELECTED_USER: 'CHANGE_SELECTED_USER',
    DELETE_USER_TASK: 'DELETE_USER_TASK',
    DONE_USER_TASK: 'DONE_USER_TASK',
    EDIT_USER_TASK: 'EDIT_USER_TASK',
    ADD_USER_TASK: 'ADD_USER_TASK',
    SAVING_USER_TASK: 'SAVING_USER_TASK',
    FETCHING_USER_DATA: 'FETCHING_USER_DATA',
  }
}
